import React from 'react';

/**
 * Simple component for displaying the results of a generated quiz.
 *
 * It iterates over `quiz.questions` and uses the following priority for
 * React keys:
 *   1. `mcq.mcq_id` (unique per item generated by the backend)
 *   2. `mcq.question_hash` (stable hash of the question text)
 *   3. array index (last resort – should never be needed in normal usage)
 *
 * Using a dedicated key prevents the "Encountered two children with the
 * same key" warning even if multiple questions happen to share the same
 * hash (e.g. identical questions returned by the generator).
 */
const QuizViewer = ({ quiz }) => {
  if (!quiz || !Array.isArray(quiz.questions)) {
    return null;
  }

  return (
    <div className="quiz-viewer space-y-6">
      {quiz.questions.map((mcq, idx) => {
        const key = mcq.mcq_id || mcq.question_hash || idx;
        return (
          <div key={key} className="mcq-item p-4 border rounded-lg bg-white">
            <p className="font-semibold text-gray-800">{mcq.question}</p>
            <ul className="list-disc list-inside mt-2">
              {mcq.options.map((opt, j) => (
                <li key={j} className="text-gray-700">
                  {opt}
                </li>
              ))}
            </ul>
          </div>
        );
      })}
    </div>
  );
};

export default QuizViewer;
